// <auto-generated />
using DbServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBServer.Migrations
{
    [DbContext(typeof(MonstersContext))]
    partial class MonstersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbServer.Data.Monsters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AC")
                        .HasColumnType("int");

                    b.Property<int>("AtackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AtackPerRound")
                        .HasColumnType("int");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("DamagePerRound")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("MinACtoAlwaysHit")
                        .HasColumnType("int");

                    b.Property<string>("MonsterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weapon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MonstersData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AC = 0,
                            AtackModifier = 0,
                            AtackPerRound = 0,
                            Damage = 0,
                            DamagePerRound = 0,
                            HitPoints = 59,
                            MinACtoAlwaysHit = 0,
                            MonsterName = "Griffon",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 2,
                            AC = 0,
                            AtackModifier = 0,
                            AtackPerRound = 0,
                            Damage = 0,
                            DamagePerRound = 0,
                            HitPoints = 24,
                            MinACtoAlwaysHit = 0,
                            MonsterName = "Swarm of rats",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 3,
                            AC = 0,
                            AtackModifier = 0,
                            AtackPerRound = 0,
                            Damage = 0,
                            DamagePerRound = 0,
                            HitPoints = 40,
                            MinACtoAlwaysHit = 0,
                            MonsterName = "Mage",
                            Weapon = 0
                        },
                        new
                        {
                            Id = 4,
                            AC = 21,
                            AtackModifier = 5,
                            AtackPerRound = 0,
                            Damage = 0,
                            DamagePerRound = 0,
                            HitPoints = 187,
                            MinACtoAlwaysHit = 0,
                            MonsterName = "Fire giant dreadnought",
                            Weapon = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
